/*
 * ============================================================================
 * FILE: models.js — DATA MODELS / DATABASE STRUCTURE DOCUMENTATION
 * ============================================================================
 *
 * WHAT THIS FILE DOES:
 * --------------------
 * This file documents the SHAPE (structure) of every data collection stored
 * in our Firestore database. It shows what fields each type of record has.
 *
 * Think of it as a "blueprint" or "template" for our data. Just like a
 * form template shows what fields need to be filled in, these models show
 * what fields each database record contains.
 *
 * NOTE: These models are NOT enforced by the code — they're mostly for
 * documentation purposes so developers know what data to expect.
 * Firestore is "schema-less", meaning it doesn't require a fixed structure.
 *
 * TECHNICAL TERMS EXPLAINED:
 * --------------------------
 * - "Collection": A group of related documents in Firestore (like a table in SQL).
 *   Example: The "users" collection contains all user profiles.
 *
 * - "Document": A single record within a collection (like a row in a table).
 *   Each document has a unique ID and contains fields (data).
 *   Example: One user document might be: { name: "Amul", role: "student" }
 *
 * - "Document ID": The unique identifier for each document.
 *   Some are auto-generated by Firestore, others we set manually.
 *   Example: For users, we use the Firebase Auth UID as the document ID.
 *
 * - "Firestore Timestamp": A special date/time format used by Firestore.
 *   It stores the exact moment something happened (down to the nanosecond).
 *   Created using serverTimestamp() which uses the server's clock.
 *
 * - "Schema": The defined structure of data. "What fields does this record have?"
 *
 * CONNECTIONS:
 * -----------
 * - These models describe the data used by:
 *   src/services/firestoreService.js (reads/writes this data)
 *   src/services/authService.js (creates user documents)
 * - Every screen that displays data relies on these structures
 * - The firestore.rules file controls who can read/write these collections
 */

// ─── USERS COLLECTION ─────────────────────────────
// Collection path in Firestore: /users/{userId}
// Document ID = Firebase Auth UID (the unique ID Firebase gives each user at signup)
//
// This stores the profile information for every registered user (students AND admins).
// Created when a user signs up (in authService.js → registerUser).

const UserModel = {
  _id: '',           // string — Firebase Auth UID (same as the document ID in Firestore)
  name: '',          // string — Full name e.g. "Amul Rai" (first + last combined)
  firstName: '',     // string — First name only, e.g. "Amul"
  lastName: '',      // string — Last name only, e.g. "Rai"
  email: '',         // string — Campus email address, e.g. "amul@campus.edu"
  passwordHash: '',  // string — NOT actually used; Firebase Auth handles passwords securely
  role: '',          // string — The user's role: 'student' | 'organizer' | 'admin'
  studentId: '',     // string — College roll number, e.g. "PST-25-0122"
  createdAt: null,   // Firestore Timestamp — When the account was created
}

// ─── MOVIES COLLECTION ────────────────────────────
// Collection path in Firestore: /movies/{movieId}
// Document ID = auto-generated by Firestore (a random unique string)
//
// Each document represents a movie that a student has suggested.
// Movies start as "not approved" (isApproved: false). An admin must approve
// them before they can be included in a poll for voting.
// Created when a student submits a suggestion (in firestoreService.js → suggestMovie).

const MovieModel = {
  _id: '',              // string — Auto-generated Firestore document ID
  title: '',            // string — The movie's name, e.g. "The Dark Knight"
  posterUrl: '',        // string — URL to the movie poster image (optional, can be empty)
  description: '',      // string — A short description of the movie
  genre: '',            // string — The movie's genre, e.g. "Sci-Fi", "Action", "Comedy"
  language: '',         // string — Language of the movie, e.g. "English", "Hindi"
  duration: '',         // string — How long the movie is, e.g. "169 min"
  suggestedBy: '',      // string — The userId (UID) of the student who suggested this movie
  isApproved: false,    // boolean — Has an admin approved this movie? (true/false)
  createdAt: null,      // Firestore Timestamp — When the suggestion was submitted
}

// ─── POLLS COLLECTION ─────────────────────────────
// Collection path in Firestore: /polls/{pollId}
// Document ID = auto-generated by Firestore
//
// A poll is a voting session where students choose which movie to watch.
// An admin creates a poll with a title and a list of approved movies.
// Only ONE poll can be "active" at a time.
// Created by admin (in firestoreService.js → createPoll).

const PollModel = {
  _id: '',              // string — Auto-generated Firestore document ID
  title: '',            // string — The poll's name, e.g. "Friday Movie Night"
  movieIds: [],         // array of strings — List of approved movie document IDs included in this poll
  startTime: null,      // Firestore Timestamp — When the poll opens for voting
  endTime: null,        // Firestore Timestamp — When the poll closes (deadline)
  status: '',           // string — Current state: 'active' (voting open) | 'closed' (voting ended) | 'upcoming'
  createdBy: '',        // string — The userId (UID) of the admin who created this poll
  totalVotes: 0,        // number — Total number of votes cast (incremented each time someone votes)
  winnerMovieId: '',    // string — The movieId of the winning movie (set when poll closes)
  createdAt: null,      // Firestore Timestamp — When the poll was created
}

// ─── VOTES COLLECTION ─────────────────────────────
// Collection path in Firestore: /votes/{voteId}
// Document ID = "{userId}_{pollId}" (this format ensures each user can only vote ONCE per poll)
//
// NOTE: The combination of userId + pollId MUST be unique.
// This prevents a student from voting twice in the same poll.
// If they try, firestoreService.js checks for an existing vote and blocks it.
// Created when a student votes (in firestoreService.js → submitVote).

const VoteModel = {
  _id: '',        // string — Format: "{userId}_{pollId}" (ensures one vote per user per poll)
  userId: '',     // string — The UID of the student who voted
  pollId: '',     // string — The ID of the poll they voted in
  movieId: '',    // string — The ID of the movie they voted for
  createdAt: null // Firestore Timestamp — When the vote was cast
}

// Export all models so other files can reference them if needed.
export { UserModel, MovieModel, PollModel, VoteModel }
