// ─── USERS COLLECTION ─────────────────────────────
// Collection path: /users/{userId}
// Document ID = Firebase Auth UID

const UserModel = {
  _id: '',           // string — Firebase Auth UID (same as document ID)
  name: '',          // string — full name e.g. "Amul Rai"
  firstName: '',     // string
  lastName: '',      // string
  email: '',         // string — campus email
  passwordHash: '',  // string — handled by Firebase Auth, stored for reference only
  role: '',          // string — 'student' | 'organizer' | 'admin'
  studentId: '',     // string — roll number e.g. "PST-25-0122"
  createdAt: null,   // Firestore Timestamp
}

// ─── MOVIES COLLECTION ────────────────────────────
// Collection path: /movies/{movieId}
// Document ID = auto-generated by Firestore

const MovieModel = {
  _id: '',              // string — auto Firestore doc ID
  title: '',            // string — movie name
  posterUrl: '',        // string — image URL (optional)
  description: '',      // string — short description
  genre: '',            // string — e.g. "Sci-Fi", "Action"
  language: '',         // string — e.g. "English", "Hindi"
  duration: '',         // string — e.g. "169 min"
  suggestedBy: '',      // string — userId of student who suggested
  isApproved: false,    // boolean — admin must approve before poll
  createdAt: null,      // Firestore Timestamp
}

// ─── POLLS COLLECTION ─────────────────────────────
// Collection path: /polls/{pollId}
// Document ID = auto-generated by Firestore

const PollModel = {
  _id: '',              // string — auto Firestore doc ID
  title: '',            // string — e.g. "Friday Movie Night"
  movieIds: [],         // array of strings — approved movie document IDs
  startTime: null,      // Firestore Timestamp
  endTime: null,        // Firestore Timestamp
  status: '',           // string — 'active' | 'closed' | 'upcoming'
  createdBy: '',        // string — userId of admin/organizer
  totalVotes: 0,        // number — updated by Cloud Function
  winnerMovieId: '',    // string — set when poll closes
  createdAt: null,      // Firestore Timestamp
}

// ─── VOTES COLLECTION ─────────────────────────────
// Collection path: /votes/{voteId}
// Document ID = "{userId}_{pollId}" (ensures uniqueness)
// NOTE: userId + pollId MUST be unique (one vote per user per poll)

const VoteModel = {
  _id: '',        // string — format: "{userId}_{pollId}"
  userId: '',     // string — who voted
  pollId: '',     // string — which poll
  movieId: '',    // string — which movie they voted for
  createdAt: null // Firestore Timestamp
}

export { UserModel, MovieModel, PollModel, VoteModel }
